INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_STEERINGVECTOR steeringVector)

FIND_PATH(
    STEERINGVECTOR_INCLUDE_DIRS
    NAMES steeringVector/api.h
    HINTS $ENV{STEERINGVECTOR_DIR}/include
        ${PC_STEERINGVECTOR_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    STEERINGVECTOR_LIBRARIES
    NAMES gnuradio-steeringVector
    HINTS $ENV{STEERINGVECTOR_DIR}/lib
        ${PC_STEERINGVECTOR_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(STEERINGVECTOR DEFAULT_MSG STEERINGVECTOR_LIBRARIES STEERINGVECTOR_INCLUDE_DIRS)
MARK_AS_ADVANCED(STEERINGVECTOR_LIBRARIES STEERINGVECTOR_INCLUDE_DIRS)

